apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: workflow-1
on:
  push:
    branches:
      - main
jobs:
  build:
    steps:
      - name: Checkout code
        uses: https://github.com/cloudbees-io/checkout@v1
      - name: Build application
        uses: docker://maven:3.8-openjdk-11
        run: |
          mvn clean package
