name: Maven Java Build

on:
  push:
    branches:
      - main
  workflow_dispatch: # Enables manual triggering from the CloudBees UI

jobs:
  build:
    steps:
      - name: Checkout Repository
        uses: cloudbees-io/checkout@v1

      - name: Compile and Test
        uses: docker://maven:3.9.6-eclipse-temurin-17
        run: mvn -B clean verify
